######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 27 09:50:21 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
